---

# Install mariaDB and init databases
- hosts: icinga_db
  become: True
  roles:
    name: geerlingguy.mysql
  vars:
    mysql_databases:
      - name: "{{icinga2_feature_idoMysql_dbname}}"
        collation: utf8_general_ci
        encoding: utf8
      - name: "{{icingaweb2_dbname}}"
        collation: utf8_general_ci
        encoding: utf8
    mysql_users:
      - name: "{{icinga2_feature_idoMysql_user}}"
        host: "%"
        password: "{{icinga2_feature_idoMysql_passwd}}"
        priv: "{{icinga2_feature_idoMysql_dbname}}.*:ALL"
      - name: "{{icingaweb2_user}}"
        host: "%"
        password: "{{icingaweb2_passwd}}"
        priv: "{{icingaweb2_dbname}}.*:ALL"
