---
# gather facts from hosts and dump them to a directory
- name: getfacts
  import_playbook: 001_getfacts.yml

# Apply common configuration to all hosts
- name: basic
  import_playbook: 002_basic.yml

# Install mariaDB and init databases
- name: Install rdbms
  import_playbook: 003a_mariadb.yml

- hosts: all
  become: True
  tasks: 
    - meta: flush_handlers 

# Install and configure icinga2
- name: Install and configure icinga2
  import_playbook: 004_icinga2.yml

- hosts: all
  become: True
  tasks: 
    - meta: flush_handlers 

# Install and configure icinga2
- name: Install and configure icingaweb2
  import_playbook: 005_icingaweb2.yml
